#!/usr/bin/env python2.7

###########
# IMPORTS #
###########

import sys
import argparse
import socket
import dns
import dns.resolver
import dns.reversename
from multiprocessing import Pool
#from multiprocessing.dummy import Pool  # utilise threads rather than subprocesses
import signal


####################
# GLOBAL VARIABLES #
####################

global nameserver


#############
# FUNCTIONS #
#############

def reverse_resolve(address):
    max_attempts = 3
    resolver = dns.resolver.get_default_resolver()
    resolver.nameservers = [nameserver]
    resolver.lifetime = 3
    attempt = 0
    while attempt < max_attempts:
        try:
            addr = dns.reversename.from_address(address)
            hosts = resolver.query(addr, 'PTR')
        except (dns.resolver.NXDOMAIN, dns.resolver.NoAnswer):
            #sys.stderr.write('%s => No record found.\n' % (address))
            pass
        except dns.resolver.Timeout:
            attempt += 1
            if attempt == max_attempts:
                sys.stderr.write('%s => Request timed out.\n' % (address))
            continue
        except (dns.resolver.NoNameservers):
            sys.stderr.write('%s => Invalid nameserver.\n' % (address))
        else:
            for host in hosts:
                host = str(host)[:-1] # slice the trailing dot
                sys.stdout.write('%s,%s\n' % (address, host))
                sys.stdout.flush()
        # break out of the loop
        attempt = max_attempts


def initializer():
    """Ignore CTRL+C in the worker process."""
    signal.signal(signal.SIGINT, signal.SIG_IGN)


########
# MAIN #
########

if __name__ == '__main__':
    desc = 'Perform reverse DNS lookup on supplied IP addresses and output results in CSV format.'

    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('-n', '--nameserver',
                        action='store',
                        help='nameserver to use for lookups (default: 8.8.8.8)',
                        metavar='SERVER',
                        default='8.8.8.8')
    parser.add_argument('file',
                        nargs='?',
                        type=argparse.FileType('r'),
                        action='store',
                        help='file containing a list of IP addresses split by a newline, otherwise read from STDIN',
                        metavar='FILE',
                        default=sys.stdin)
    args = parser.parse_args()

    global nameserver
    nameserver = args.nameserver

    try:
        addresses = [line.strip() for line in args.file if len(line.strip())>0 and line[0] is not '#']
    except KeyboardInterrupt:
        exit()

    # remove duplicates
    addresses = list(set(addresses))

    # sort
    addresses = sorted(addresses, key=lambda item: socket.inet_aton(item))

    # https://www.binpress.com/tutorial/simple-python-parallelism/121
    pool = Pool(processes=10, initializer=initializer)
    try:
        pool.map(reverse_resolve, addresses)
        pool.close()
        pool.join()
    except KeyboardInterrupt:
        pool.terminate()
        pool.join()

