#!/usr/bin/env ruby

$stderr.sync = true

begin
  require 'rex/socket'
rescue LoadError
  STDERR.puts "The rex-socket gem could not be loaded, is it installed?"
  STDERR.puts "-> gem install rex-socket"
  exit
end

ARGF.each_line do |range|
  ip_list = Rex::Socket::RangeWalker.new(range)
  if ip_list.length == 0
    STDERR.puts "[-] The line '#{range}' appears to be invalid!"
    exit
  else
    ip_list.each do |i|
      puts i
    end
  end
end
