#!/usr/bin/env ruby

$stderr.sync = true

require 'rex/socket'
require 'optparse'

ARGF.each_line do |range|
  ip_list = Rex::Socket::RangeWalker.new(range)
  if ip_list.length == 0
    STDERR.puts "[-] The line '#{range}' appears to be invalid!"
    exit
  else
    ip_list.each do |i|
      puts i
    end
  end
end
