#!/usr/bin/env ruby

$stderr.sync = true
require 'nmap/xml'
require 'sablon'
require 'optparse'
require 'csv'

# default options
output = ''
vhosts= ''
input  = Array.new


# parse arguments
file = __FILE__
ARGV.options do |opts|
  opts.on("-o", "--output FILE", String)            { |val| output = val }
  opts.on("-n", "--hostnames FILE", String)         { |val| vhosts = val }
  opts.on("-i", "--input FILE1,FILE2,FILE3", Array) { |val| input = val }
  opts.on_tail("-h", "--help")                        { puts opts; exit }
  opts.parse!
end

if output.nil? or output.empty? then
  puts "Missing option: output"
  puts ARGV.options
  exit
end

if input.empty? then
  puts "Missing option: input"
  puts ARGV.options
  exit
end

input.each do |file|
  if not File.exists?(file)
    puts "#{file} does not exist!"
    exit 1
  end
end

hostnames = Hash.new

unless vhosts.empty? then
  if not File.exists?(vhosts)
    puts "#{vhosts} does not exist!"
    exit 1
  else
    puts "[+] Reading #{vhosts} ..."
    CSV.foreach(vhosts) do |row|
      hostname = row[1].strip
      ip = row[2].strip
      unless hostname.empty?
        if not hostnames.key? ip
          hostnames[ip] = Array.new
        end
        hostnames[ip] << hostname
      end
    end
  end
end

hosts = Hash.new

input.each do |nmap|
  puts "[+] Processing #{nmap} ..."
  Nmap::XML.new(nmap) do |xml|
    xml.each_host do |host|

      nhostnames = Array.new
      host.each_hostname do |hostname|
        if not hostnames.key? host.ip
          hostnames[host.ip] = Array.new
        end
        hostnames[host.ip] << hostname.name.strip
      end

      host.each_port do |port|
        if port.state == :open and not port.service.nil?
          if port.service.ssl?
            name = "ssl/#{port.service.name}"
          else
            name = port.service.name
          end
          unless name == 'tcpwrapped'
            if not hosts.key? host.ip
              hosts[host.ip] = Array.new
            end
            hosts[host.ip] << { :port => port.number, :proto => port.protocol, :name => name }
          end
        end
      end

    end
  end
end

results = Array.new
hosts.each do |ip, services|
  names = Array.new
  if hostnames.key? ip
    names = hostnames[ip]
  end
  results << { :ip => ip, :hostnames => names.sort, :services => services.sort_by { |service| service[:port] } }
end

puts "[+] Generating #{output} ..."
context = { :hosts => results }
template = Sablon.template(File.expand_path(File.dirname(__FILE__) + "/nmap2docx.docx"))
template.render_to_file File.expand_path(output), context

