#!/bin/bash
# git clone https://github.com/robertdavidgraham/masscan.git

if [ -z $2 ]; 
  then printf "\nSyntax: $0 <file of ips> <rate|e.g. 2000>\n\n"
else
  FILE=$1; RATE=$2;
  echo "# masscan -iL $FILE -p T:0-65535 --rate $RATE -oB tcp.masscan" | tee masscan_tcp.out
  masscan -iL $FILE -p T:0-65535 --rate $RATE -oB tcp.masscan | tee -a masscan_tcp.out
  if [ $(ls tcp.masscan 2> /dev/null | wc -l) -gt 0 ]; then
    masscan --readscan tcp.masscan -oX tcp.xml
    masscan --readscan tcp.masscan -oL tcp.list
    cat tcp.list | grep ^open | cut -d" " -f3 | sort -n | uniq > ports.list
    chown $USER:$USER tcp.* ports.list masscan_tcp.out
  fi
fi
