#!/usr/bin/env python2.7

import sys
import requests
from lxml.html import fromstring

def clean(content):
    if content is None:
        return ''
    content = content.strip()
    if content.lower() == 'n/a' or content.lower() == 'n.a' or content.lower() == '(none)' or content.lower() == '(blank)':
        content = ''
    return content

def ignore(protocol, user, password):
    if 'ast 6 characters' in password:
        return True
    if 'characters of the' in password:
        return True
    if '0 and the number of OCE printer' in password:
        return True
    if 'use ALT+G' in password:
        return True
    return False

response = requests.get('http://www.defaultpassword.com/')
page = fromstring(response.text)
rows = page.xpath("//table")[1].findall("tr")
data = list()

for row in rows:
    data.append([c.text for c in row.getchildren()])

for row in data[3:]:
    protocol = clean(row[3].lower())
    username = clean(row[4])
    password = clean(row[5])

    if ignore(protocol, username, password):
        continue

    if password == 'password/changeme or secret':
        print "%s,%s,%s" % (protocol, username, 'password')
        print "%s,%s,%s" % (protocol, username, 'changeme')
        print "%s,%s,%s" % (protocol, username, 'secret')
        continue
    if password == 'public/private/secret':
        print "%s,%s,%s" % (protocol, username, 'public')
        print "%s,%s,%s" % (protocol, username, 'private')
        print "%s,%s,%s" % (protocol, username, 'secret')
        continue

    sys.stdout.write('%s,%s,%s\n' % (protocol, username, password))
    sys.stdout.flush()
