#!/bin/bash

VMRUN_BIN="/Applications/VMware Fusion.app/Contents/Library/vmrun"
LIBRARY="$HOME/Documents/Virtual Machines.localized"

case "$1" in
  list)
    find "$LIBRARY" -name "*.vmx" | while read line; do
        filename=$(basename "$line")
        echo "${filename%.*}"
    done
    exit 0
    ;;
  status)
    "$VMRUN_BIN" list
    exit 0
    ;;
  *)
    if [ ! -f "/Users/sion/Documents/Virtual Machines.localized/$1.vmwarevm/$1.vmx" ]
      then
        echo "Usage: possible options are:"
        echo "vm <vm> { start | stop | suspend | pause | unpause | reset | ip } | status"
        exit 1
    fi
esac

VM="/Users/sion/Documents/Virtual Machines.localized/$1.vmwarevm/$1.vmx"

case "$2" in
  start)
    "$VMRUN_BIN" start "$VM" nogui
    ;;
  stop)
    "$VMRUN_BIN" stop "$VM" nogui
    ;;
  suspend)
    "$VMRUN_BIN" suspend "$VM" nogui
    ;;
  pause)
    "$VMRUN_BIN" pause "$VM" nogui
    ;;
  unpause)
    "$VMRUN_BIN" unpause "$VM" nogui
    ;;
  reset)
    "$VMRUN_BIN" reset "$VM" nogui
    ;;
  ip)
    "$VMRUN_BIN" getGuestIPAddress "$VM" nogui
    ;;
  status)
    "$VMRUN_BIN" list
    ;;
  *)
    echo "Usage: possible options are:"
    echo "vm <vm> { start | stop | suspend | pause | unpause | reset | ip } | status"
    exit 1
esac
