apt install \
alsa-base \
alsa-utils \
anacron \
baloo-kf5 \
bc \
breeze \
ca-certificates \
foomatic-db-compressed-ppds \
genisoimage \
ghostscript-x \
inputattach \
kde-cli-tools \
khotkeys \
kinfocenter \
kio \
kio-extras \
kmenuedit \
ksysguard \
kwin-x11 \
kwrited \
libsasl2-modules \
memtest86+ \
openprinting-ppds \
oxygen-sounds \
plasma-desktop \
pm-utils \
powerdevil \
printer-driver-pnm2ppa \
rfkill \
sddm-theme-breeze \
systemsettings \
unzip \
wireless-tools \
wpasupplicant \
xdg-user-dirs \
xkb-data \
xorg \
zip \
acpi-support \
ark \
avahi-autoipd \
avahi-daemon \
bluedevil \
bluez \
bluez-cups \
cdrdao \
cryptsetup \
cups \
cups-bsd \
cups-client \
cups-filters \
dolphin \
frameworkintegration \
fwupd \
fwupdate \
gwenview \
hplip \
kde-config-gtk-style \
kde-config-gtk-style-preview \
kde-config-sddm \
kde-spectacle \
kimageformat-plugins \
konsole \
kscreen \
ksshaskpass \
kwin-addons \
kwrite \
laptop-detect \
libnss-mdns \
libqca2-plugin-ossl \
milou \
mobile-broadband-provider-info \
pcmciautils \
phonon-backend-vlc \
phonon4qt5-backend-vlc \
plasma-dataengines-addons \
plasma-discover \
plasma-discover-updater \
plasma-nm \
plasma-pa \
plasma-runners-addons \
plasma-wallpapers-addons \
plasma-widgets-addons \
polkit-kde-agent-1 \
print-manager \
printer-driver-brlaser \
printer-driver-c2esp \
printer-driver-foo2zjs \
printer-driver-min12xxw \
printer-driver-ptouch \
printer-driver-pxljr \
printer-driver-sag-gdi \
printer-driver-splix \
pulseaudio \
pulseaudio-module-bluetooth \
qml-module-qtgraphicaleffects \
qml-module-qtquick-xmllistmodel \
qt5-default \
qt5-image-formats-plugins \
udisks2 \
upower \
user-manager \
vlc \
xdg-utils